# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 21 May 2025 16:43:30 +0200
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated
# Password: DevTest2025!
admin:$2y$10$8Uc1ELiFnFpGlpLSpSxqXuePxTLgITYte1NXxlETqM4ZJjcme24wG:Michael Wegener:mw@satware.com:admin,user
