# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 21 May 2025 16:43:30 +0200
*               @ALL          1
*               @user         8
*               admin         16
