<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 21 May 2025 17:00:36 +0200
 */

$conf['title'] = 'DokuWiki Manager Dev';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = '';
// Enable XML-RPC / JSON-RPC interface
$conf['remote'] = 1;

// Disable some security features for development
$conf['securecookie'] = 0;
$conf['xmlrpc'] = 1;

// Allow all methods for remote API
$conf['remotecors'] = '*';

// Easy debugging
$conf['allowdebug'] = 1;